// This file is automatically generated
namespace Dream {
	const char * const SCM_SHORT_ID = "c0b4ead";
	const char * const SCM_LONG_ID = "c0b4eadff4b6d3b52657ee6259b19e5f10764bbf";
	const char * const BUILD_DATE = "2012-08-23 15:34:23";
	const char * const BUILD_PLATFORM = "Darwin 12.0.0 i386";
}
