// This file is automatically generated
namespace Dream {
	const char * const SCM_SHORT_ID = "34e4430";
	const char * const SCM_LONG_ID = "34e44309041c63d7064ed7937a4632a4fc06e1ca";
	const char * const BUILD_DATE = "2010-04-24 13:29:14";
	const char * const BUILD_PLATFORM = "Darwin 10.3.0 i386";
}
