// This file is automatically generated
 *  Revision.h
 *  This file is part of the "Dream" project, and is licensed under the GNU GPLv3.
 *
	const char * const BUILD_DATE = "2009-04-26 08:57:22";
	const char * const BUILD_PLATFORM = "Darwin 9.6.0 i386";
}
